<template>
  <button @click="cl" class="btn">
    <Icone_back style="margin-right: 11px" />BACK
  </button>
  <div class="profile">
    <!-- <div class="img"></div> -->
    <img class="img" :src="img" />
    <div class="list">
      <span class="header header1">LOS SANTOS POLICE DEP.</span>
      <span class="header header2"> CRIMINAL RECORD</span>
      <span><span class="bold">name:</span> {{ this.list.Fistname }}</span>
      <span>
        <span class="bold">Lastname: </span> {{ this.list.Lastname }}</span
      >
      <span> <span class="bold">id: </span>{{ this.list.id }}</span>
      <span> <span class="bold">Height: </span>{{ this.list.height }}</span>
      <span> <span class="bold">Birthday: </span>{{ this.list.birthday }}</span>
      <span> <span class="bold">Age: </span>{{ this.list.age }}</span>
      <span> <span class="bold">Sex: </span>{{ this.list.sex }}</span>
      <span>
        <span class="bold">Ethnicity: </span>{{ this.list.ethnicity }}</span
      >
      <span> <span class="bold">Phone: </span>{{ this.list.phone }}</span>
      <span> <span class="bold">Addres: </span>{{ this.list.addres }}</span>
    </div>
    <div class="icon_container">
      <div class="plate"></div>
      <span class="b">GENERATED BY THE STATE COMPUTER</span>
      <span class="a1">File number: #123456789</span>
      <img src="@/icons/logo.png" style="margin-top: 35px" />
    </div>
  </div>
  <h1>Record History</h1>
  <div class="list2_head">
    <span>DATE</span>
    <span>OFFENCE CODE</span>
    <span>STATIONS</span>
    <span>MOTIVE</span>
    <span>TERM</span>
  </div>
  <div class="list2_container">
    <div v-for="crime in this.list.history" class="list2">
      <!-- props: ["date", "code", "stations", "motive", "term"], -->
      <Criminal_profile_list
        :date="crime.date"
        :code="crime.code"
        :stations="crime.stations"
        :motive="crime.motive"
        :term="crime.term"
      />
    </div>
  </div>
  <span class="c1">Fingerprints</span>

  <div class="a">
    <div class="prints_container prints_container1">
      <span class="print_item thumb">1.THUMB</span>
      <span class="print_item index">2.INDEX FINGER</span>
      <span class="print_item middle">3.MIDDLE FINGER</span>
      <span class="print_item ring">4.RING FINGER</span>
      <span class="print_item little">5.LITTLE FINGER</span>
      <div class="print_item finger1">
        <Finger1 />
      </div>
      <div class="print_item finger2">
        <Finger1 />
      </div>
      <div class="print_item finger3">
        <Finger1 />
      </div>
      <div class="print_item finger4">
        <Finger1 />
      </div>
      <div class="print_item finger5">
        <Finger1 />
      </div>
    </div>
    <div class="prints_container prints_container2">
      <span class="print_item thumb">1.THUMB</span>
      <span class="print_item index">2.INDEX FINGER</span>
      <span class="print_item middle">3.MIDDLE FINGER</span>
      <span class="print_item ring">4.RING FINGER</span>
      <span class="print_item little">5.LITTLE FINGER</span>
      <div class="print_item finger1">
        <Finger1 />
      </div>
      <div class="print_item finger2">
        <Finger1 />
      </div>
      <div class="print_item finger3">
        <Finger1 />
      </div>
      <div class="print_item finger4">
        <Finger1 />
      </div>
      <div class="print_item finger5">
        <Finger1 />
      </div>
    </div>

    <div class="other_info_container">
      <span>Other info</span>
      <div class="other_info">
        <textarea disabled>{{ this.list.otherInfo }}</textarea>
      </div>
    </div>
  </div>
</template>

<script>
import Icone_back from "@/icons/Icone_back.vue";

import Finger1 from "@/finger/Finger1.vue";
import Criminal_profile_list from "./Criminal_profile_list.vue";
export default {
  data() {
    return {
      avatar: "",
      color: "",
    };
  },
  components: { Icone_back, Finger1, Criminal_profile_list },
  props: ["list"],
  methods: {
    cl() {
      this.$emit("back", 2);
    },
  },
  computed: {
    img() {
      if (this.list.avatar) {
        return (this.avatar = this.list.avatar);
      } else {
        return (this.avatar = require("@/icons/base_avatar.png"));
      }
    },
    color() {},
  },
};
</script>

<style scoped>
@import url("https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@1,600&display=swap");

::-webkit-scrollbar {
  width: 5px;
}
::-webkit-scrollbar-track {
  width: 5px;
}

::-webkit-scrollbar-thumb {
  background-color: #464646;
  border-radius: 10px;
}

.bold {
  font-family: Arial;
  font-size: 18px;
  font-weight: 700;
  color: #222222;
}
.prints_container1 {
  order: -1;
}
.prints_container2 {
  order: 1;
}
.img {
  margin-left: 108px;
  margin-top: 38px;
  width: 268px;
  height: 268px;
  background-color: #f0f3f9;
}

.other_info_container {
  font-size: 28px;
  font-family: "Montserrat";
}

.list2_container {
  margin-bottom: 47px;
  display: flex;
  overflow: auto;
  max-height: 575px;
  justify-content: center;
  align-items: center;
  width: 1420px;
  flex-wrap: wrap;
  margin-left: 111px;
}
.other_info {
  display: flex;
  justify-content: center;
  align-items: center;
  font-family: Arial;
  font-size: 22px;
  margin-top: 21px;
  border-top: 1px solid #454545;
  border-bottom: 1px solid #454545;
  width: 495px;
  height: 368px;
}

.print_item {
  font-size: 9px;
  display: flex;
  justify-content: center;
  align-items: center;
  border: 1px solid black;
}

.a {
  margin-left: 108px;
  margin-bottom: 77px;
  display: grid;
  grid-template-columns: 760px 650px;
  grid-template-rows: 200px 200px;
  justify-items: end;
}

textarea {
  background-color: transparent;
  outline: none;
  border-style: hidden;
  font-family: Arial;
  font-size: 22px;
  width: 480px;
  height: 340px;
}

.prints_container {
  font-family: "Montserrat";
  margin-left: 112px;
  margin-top: 50px;
  display: grid;
  grid-template-columns: 151px 151px 151px 151px 151px;
  grid-template-rows: 27px 145px;
}

.c1 {
  font-family: "Montserrat";
  font-size: 28px;
  margin-left: 108px;
  margin-top: 50px;
}
.b {
  font-family: "Arial Narrow";

  margin-right: 56px;
  margin-top: 10px;
  font-size: 12px;
}

.icon_container {
  margin-left: 290px;
  width: 260px;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  justify-content: flex-end;
}

.plate {
  width: 252px;
  height: 8px;
  background-color: #464646;

  margin-top: 50px;
}

.list2 {
  font-family: Arial;
  color: #464646;
  width: 1398px;
  padding-left: 36px;
  padding-right: 84px;
  border-top: 1px solid#454545;
  border-bottom: 1px solid#454545;
  align-items: center;

  display: grid;
  grid-template-columns: 281px 192px 300px 385px 159px;

  font-size: 22px;
  height: 80px;
}
.list2_head {
  width: 1398px;
  font-family: Arial;
  font-size: 22px;
  font-weight: 600;
  padding-left: 65px;
  padding-right: 84px;
  border-top: 1px solid#454545;
  border-bottom: 1px solid#454545;
  display: grid;
  grid-template-rows: 90px;
  grid-template-columns: 183px 280px 307px 400px 400px;
  margin-top: 20px;
  margin-left: 120px;
  align-items: center;
}

h1 {
  font-size: 28px;
  margin-left: 108px;
  margin-top: 48px;
}

.profile {
  display: flex;
}

.btn {
  margin-left: 123px;
  margin-top: 59px;
  display: flex;
  justify-content: center;
  align-items: center;
  width: 60px;
  height: 24px;
  background-color: transparent;
  border-style: hidden;
}

.list {
  grid-template-areas:
    "header1 header1"
    "header2 header2";

  align-items: center;
  grid-template-columns: 200px 200px;
  grid-template-rows: 29px 29px 20px 20px 20px 20px 20px;
  row-gap: 20px;
  column-gap: 100px;
  margin-left: 40px;
  display: grid;
  color: #464646;
  margin-top: 0px;
  font-size: 18px;
}

.header1 {
  font-family: Arial;
  font-weight: 700;
  font-size: 23px;
  color: #222222;
  grid-area: header1;
  margin-top: 60px;
}
.header2 {
  margin-top: 15px;
  font-family: Arial;
  font-weight: 700;
  font-size: 16px;
  color: #222222;
  grid-area: header2;
}

img {
  margin-left: 80px;
}

@media screen and (max-width: 1401px) {
  .list2_container {
    width: 1020px;
  }
  .list2 {
    width: 1000px;
    grid-template-columns: 207px 136px 248px 210px 150px;
    font-size: 16px;
  }
  .list2_head {
    width: 1000px;
    font-size: 16px;
    grid-template-columns: 150px 200px 250px 240px 56px;
    padding-left: 45px;
    padding-right: 45px;
  }

  .img,
  .list2_head,
  .btn,
  .c,
  h1 {
    margin-left: 42px;
  }
  .list2_container {
    margin-left: 34px;
  }

  .icon_container {
    margin-left: 0px;
  }

  .other_info {
    width: 536px;
  }

  textarea {
    width: 520px;
  }
  .a {
    margin-left: 42px;
    height: 1000px;
    width: 1000px;
    display: grid;
    grid-template-columns: 151px 151px 660px;
    column-gap: 25px;
  }
  .prints_container {
    grid-template-columns: 151px;
    margin-left: 0px;
  }
  .prints_container1 {
    order: -1;
  }
  .prints_container2 {
    order: 1;
  }
  .other_info_container {
    order: 2;
  }

  .prints_container {
    grid-template-rows: repeat(10, 27px 145px);
  }
  .thumb {
    order: -1;
  }
  .finger1 {
    order: 0;
  }
  .index {
    order: 1;
  }
  .finger2 {
    order: 2;
  }
  .middle {
    order: 3;
  }
  .finger3 {
    order: 4;
  }
  .ring {
    order: 5;
  }
  .finger4 {
    order: 6;
  }
  .little {
    order: 7;
  }
  .finger5 {
    order: 8;
  }
}
</style>
